### ISSUE TITLE
i386 combinations are missing

### ISSUE THREAD

**Issue by nghiant2710** [resin-io-playground/base-img-generator#4]
After upgrading to contrato v0.0.3 (https://github.com/resin-io-modules/contrato/pull/2), `i386` combinations are no longer generated (`contrato.query` doesn't return results about `i386`).

**Comment by nghiant2710** [comment]
Actually, I run again with current master branch and `i386` combination aren't generated as well.

**Comment by jviotti** [comment]
Oh, check this out: https://github.com/resin-io-playground/base-img-generator/blob/master/bin/generate-combinations.js#L30. Looks like we're not actually importing the i386 arch contract :D Can you try if adding it there fixes the issue?

**Comment by nghiant2710** [comment]
right, that contract wasn't imported. Thanks!
